---
abstract: 'Log messages to a file(with stamp in the filename).'
author:
  - 'Dai Okabayashi <bayashi@cpan.org>'
build_requires:
  File::Spec: 0
  POSIX: 0
  Test::More: 0.88
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Handler-Output-File-Stamper
provides:
  Log::Handler::Output::File::Stamper:
    file: lib/Log/Handler/Output/File/Stamper.pm
    version: 0.03
recommends:
  Time::HiRes: 0
requires:
  Carp: 0
  Fcntl: 0
  Log::Handler: 0
  Log::Handler::Output::File: 0.06
  Log::Stamper: 0.03
  perl: v5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bayashi/Log-Handler-Output-File-Stamper
version: 0.03
